version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: dev-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Muzlive1234!
      MYSQL_DATABASE: kitpage
    ports:
      - "13306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - dev-net

  app:
    image: openjdk:11-jdk-slim
    container_name: dev-app
    working_dir: /app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    volumes:
      - ./jar:/app
      - ./logs:/app/logs
      - ./dump:/app/dump
      - /source:/source
      - /usr/local/bin/ffmpeg:/usr/local/bin/ffmpeg
      - /usr/local/bin/ffprobe:/usr/local/bin/ffprobe
    command: >
      java -Xms1024M -Xmx1536M
           -XX:+UseG1GC
           -XX:+UseStringDeduplication
           -XX:+HeapDumpOnOutOfMemoryError
           -XX:HeapDumpPath=/app/dump
           -Dlog4j2.formatMsgNoLookups=true
           -Dfile.encoding=UTF-8
           -Duser.timezone=Asia/Seoul
           -DLOG_HOME=/app/logs
           -Dspring.profiles.active=dev
           -Dspring.config.additional-location=/source/
           -jar app.jar
    networks:
      - dev-net

volumes:
  mysql-data:

networks:
  dev-net: