version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: dev-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: kitpage
    ports:
      - "13306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - dev-net

  app:
    image: openjdk:11-jdk-slim
    container_name: dev-app
    working_dir: /app
    depends_on:
      - mysql
    ports:
      - "8081:8081"
    volumes:
      - ./jar:/app
      - ./logs:/app/logs
      - ./dump:/app/dump
      - /source:/source
    environment:
      SPRING_PROFILES_ACTIVE: dev
      JAVA_OPTS: >
        -Xms2048M -Xmx2048M
        -XX:+UseG1GC
        -XX:+UseStringDeduplication
        -XX:+HeapDumpOnOutOfMemoryError
        -XX:HeapDumpPath=/app/dump
        -Dlog4j2.formatMsgNoLookups=true
        -Dfile.encoding=UTF-8
        -Duser.timezone=Asia/Seoul
        -DLOG_HOME=/app/logs
    command: sh -c "java $JAVA_OPTS -jar app.jar --spring.profiles.active=$SPRING_PROFILES_ACTIVE"
    networks:
      - dev-net

volumes:
  mysql-data:

networks:
  dev-net: