version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: dev-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: kitpage
    ports:
      - "13306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - dev-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev-app
    depends_on:
      - mysql
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - dev-net

volumes:
  mysql-data:

networks:
  dev-net: