version: 0.0
os: linux

files:
  - source: ./
    destination: /home/ec2-user/nonstop/jar
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: /source/start.sh
      timeout: 180
      runas: root
      script: chmod +x /source/start.sh
  ApplicationStop:
    - location: /source/stop.sh
      timeout: 60
      runas: root
      script: chmod +x /source/start.sh