name: Build and Deploy

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build without Test
        run: |
          echo "DEVELOP Pipeline Started!"
          ./gradlew clean
          ./gradlew build -x test --no-build-cache
        continue-on-error: false

      - name: Create .ssh directory
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

      - name: Add EC2 host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.DEV_EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Upload jar to EC2
        run: |
          echo "${{ secrets.DEV_SSH_KEY }}" > key.pem
          chmod 600 key.pem
          scp -i key.pem build/libs/kit-page-0.0.1-SNAPSHOT-boot.jar ${{ secrets.DEV_EC2_USER }}@${{ secrets.DEV_EC2_HOST }}:/home/ec2-user/nonstop/libs/

      - name: Stop Existing Application
        run: |
          ssh -i key.pem ${{ secrets.DEV_EC2_USER }}@${{ secrets.DEV_EC2_HOST }} 'bash /source/stop.sh'

      - name: Start New Application
        run: |
          ssh -i key.pem ${{ secrets.DEV_EC2_USER }}@${{ secrets.DEV_EC2_HOST }} 'bash /source/start.sh'